-- ============================================================================
-- HAMDAN-EMPLOYEE database backup — Table definitions
-- Snapshot taken: current live state as of this export.
-- Project: HAMDAN-EMPLOYEE (msoomcjzzudibiyezclj)
--
-- HOW TO USE THIS BACKUP:
-- This is a "current state" snapshot, not a chronological replay of every
-- migration ever run. If you ever need to rebuild the database from
-- scratch (e.g. new Supabase project), run these files in order:
--   01_tables.sql -> 02_indexes.sql -> 03_functions_and_triggers.sql
--   -> 04_rls_policies.sql -> 05_storage.sql
-- Some tables reference auth.users / profiles, so table creation order
-- matters -- it's already set correctly below.
-- ============================================================================

-- Core: one row per user, mirrors auth.users via same id
create table if not exists public.profiles (
  id uuid primary key references auth.users(id),
  employee_id text unique,
  full_name text,
  role text default 'employee',
  created_at timestamptz default now(),
  avatar_url text,
  designation text
);

create table if not exists public.attendance_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id),
  log_date date not null default ((current_timestamp at time zone 'Asia/Manila'::text))::date,
  time_in timestamptz default now(),
  time_out timestamptz,
  status text not null default 'Present',
  created_at timestamptz default now(),
  constraint attendance_logs_user_id_log_date_key unique (user_id, log_date)
);

create table if not exists public.announcements (
  id uuid primary key default gen_random_uuid(),
  content text not null,
  image_url text,
  updated_by uuid references public.profiles(id),
  updated_at timestamptz not null default now()
);

create table if not exists public.employee_government_ids (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.profiles(id),
  sss_number text,
  philhealth_number text,
  pagibig_number text,
  tin_number text,
  hired_date date,
  employment_status text check (employment_status is null or employment_status = any (array['Regular','Probationary','Contractual'])),
  updated_by uuid references public.profiles(id),
  updated_at timestamptz not null default now()
);

create table if not exists public.attendance_disputes (
  id uuid primary key default gen_random_uuid(),
  attendance_log_id bigint references public.attendance_logs(id),
  user_id uuid not null references public.profiles(id),
  dispute_date date not null,
  claimed_time_in timestamptz not null,
  original_time_in timestamptz,
  reason text,
  status text not null default 'Pending' check (status = any (array['Pending','Approved','Rejected'])),
  hr_notes text,
  reviewed_by uuid references public.profiles(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.payslips (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id),
  cutoff_period text not null,
  cutoff_label text not null,
  file_path text not null,
  file_name text not null,
  uploaded_by uuid references public.profiles(id),
  uploaded_at timestamptz not null default now()
);

create table if not exists public.leave_requests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id),
  leave_type text not null check (leave_type = any (array['Sick','Vacation','Emergency'])),
  start_date date not null,
  end_date date not null,
  reason text,
  status text not null default 'Pending' check (status = any (array['Pending','Approved','Rejected'])),
  hr_notes text,
  reviewed_by uuid references public.profiles(id),
  reviewed_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.leave_credits (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id),
  year integer not null,
  total_credits integer not null default 15,
  used_credits integer not null default 0,
  constraint leave_credits_user_id_year_key unique (user_id, year)
);

-- Per-day breakdown of an approved leave request. Each weekday in a leave's
-- date range (excluding holidays) gets one row here, which is only settled
-- to 'Deducted' or 'Voided' once we can confirm whether the employee
-- actually stayed out that specific day. See settle_leave_day() below.
create table if not exists public.leave_request_days (
  id uuid primary key default gen_random_uuid(),
  leave_request_id uuid not null references public.leave_requests(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  leave_date date not null,
  status text not null default 'Pending' check (status in ('Pending','Deducted','Voided')),
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  unique (leave_request_id, leave_date)
);

-- Declared non-working days (national holidays, company closures, etc).
-- Referenced by both the absence sweep and the leave-day generator so
-- these dates never get auto-marked Absent nor charged as leave.
create table if not exists public.holidays (
  id uuid primary key default gen_random_uuid(),
  holiday_date date not null unique,
  name text not null,
  created_by uuid references public.profiles(id),
  created_at timestamptz not null default now()
);

-- ============================================================================
-- Archive tables (1-year data retention). Same columns as their live
-- counterparts, deliberately WITHOUT foreign keys -- archived rows are
-- historical only and shouldn't stay referentially tied to (possibly
-- also-archived) parent rows. Populated only by archive_old_records().
-- ============================================================================

create table if not exists public.attendance_logs_archive (like public.attendance_logs including defaults);
create table if not exists public.attendance_disputes_archive (like public.attendance_disputes including defaults);
create table if not exists public.leave_requests_archive (like public.leave_requests including defaults);
create table if not exists public.leave_request_days_archive (like public.leave_request_days including defaults);
